package learnway.components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import learnway.model.Model_Admin_Card;


public class AdminDashboardCard extends javax.swing.JPanel {
    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    private Color color1;
    private Color color2;

    public AdminDashboardCard() {
        initComponents();
        setOpaque(false);
        color1 = Color.BLACK;
        color2 = Color.WHITE;
    }

    public void setData(Model_Admin_Card data) {
        lbUser.setText(data.getUser());
        lbCount.setText(data.getCount());

    }

  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUser = new javax.swing.JLabel();
        lbCount = new javax.swing.JLabel();

        setLayout(null);

        lbUser.setFont(lbUser.getFont().deriveFont(lbUser.getFont().getStyle() | java.awt.Font.BOLD, lbUser.getFont().getSize()+6));
        lbUser.setForeground(new java.awt.Color(255, 255, 255));
        lbUser.setText("User");
        add(lbUser);
        lbUser.setBounds(30, 40, 160, 25);

        lbCount.setFont(lbCount.getFont().deriveFont(lbCount.getFont().getStyle() | java.awt.Font.BOLD, lbCount.getFont().getSize()+6));
        lbCount.setForeground(new java.awt.Color(255, 255, 255));
        lbCount.setText("Count");
        add(lbCount);
        lbCount.setBounds(30, 90, 160, 25);
    }// </editor-fold>//GEN-END:initComponents

       @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255, 255, 255, 50));
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCount;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
