package learnway.components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import learnway.model.Model_Card;
import learnway.model.Model_Exam_Schedule;


public class ExamScheduleCard extends javax.swing.JPanel {
    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    private Color color1;
    private Color color2;

    public ExamScheduleCard() {
        initComponents();
        setOpaque(false);
        color1 = Color.BLACK;
        color2 = Color.WHITE;
    }

    public void setData(Model_Exam_Schedule data) {;
        lbyear.setText(data.getYear());
        lblanguage.setText(data.getLanguage());
        lbtime.setText(data.getTime());
        lbdate.setText(data.getDate());
        lbstatus.setText(data.getStatus());

    }

  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbyear = new javax.swing.JLabel();
        lblanguage = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(null);

        lbyear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbyear.setForeground(new java.awt.Color(255, 255, 255));
        lbyear.setText("Year");
        add(lbyear);
        lbyear.setBounds(30, 20, 38, 25);

        lblanguage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblanguage.setForeground(new java.awt.Color(255, 255, 255));
        lblanguage.setText("Status");
        add(lblanguage);
        lblanguage.setBounds(30, 140, 53, 25);

        lbtime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbtime.setForeground(new java.awt.Color(255, 255, 255));
        lbtime.setText("Language");
        add(lbtime);
        lbtime.setBounds(30, 50, 83, 25);

        lbdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbdate.setForeground(new java.awt.Color(255, 255, 255));
        lbdate.setText("Time");
        add(lbdate);
        lbdate.setBounds(30, 80, 42, 25);

        lbstatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbstatus.setForeground(new java.awt.Color(255, 255, 255));
        lbstatus.setText("Date");
        add(lbstatus);
        lbstatus.setBounds(30, 110, 40, 25);
    }// </editor-fold>//GEN-END:initComponents

       @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255, 255, 255, 50));
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lblanguage;
    private javax.swing.JLabel lbstatus;
    private javax.swing.JLabel lbtime;
    private javax.swing.JLabel lbyear;
    // End of variables declaration//GEN-END:variables
}
