/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package learnway.view.admin;

import javax.swing.JPanel;
import learnway.view.Main;

/**
 *
 * @author tehan
 */
public class AcademicAddNew extends javax.swing.JPanel {
private Main l;
    /**
     * Creates new form AddNewAcademic
     */
    public AcademicAddNew(Main m) {
        this.l = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        typeAreajPanel7 = new javax.swing.JPanel();
        filedJLable8 = new javax.swing.JLabel();
        detailTypeTextField8 = new learnway.components.TextField();
        typeAreajPanel9 = new javax.swing.JPanel();
        filedJLable10 = new javax.swing.JLabel();
        detailTypeTextField10 = new learnway.components.TextField();
        typeAreajPanel8 = new javax.swing.JPanel();
        typeAreajPanel10 = new javax.swing.JPanel();
        filedJLable11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        typeAreajPanel11 = new javax.swing.JPanel();
        filedJLable12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        typeAreajPanel12 = new javax.swing.JPanel();
        filedJLable13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        typeAreajPanel = new javax.swing.JPanel();
        filedJLable1 = new javax.swing.JLabel();
        detailTypeTextField1 = new learnway.components.TextField();
        typeAreajPanel1 = new javax.swing.JPanel();
        filedJLable2 = new javax.swing.JLabel();
        detailTypeTextField2 = new learnway.components.TextField();
        typeAreajPanel2 = new javax.swing.JPanel();
        filedJLable3 = new javax.swing.JLabel();
        detailTypeTextField3 = new learnway.components.TextField();
        typeAreajPanel3 = new javax.swing.JPanel();
        filedJLable4 = new javax.swing.JLabel();
        detailTypeTextField4 = new learnway.components.TextField();
        typeAreajPanel4 = new javax.swing.JPanel();
        filedJLable5 = new javax.swing.JLabel();
        detailTypeTextField5 = new learnway.components.TextField();
        typeAreajPanel5 = new javax.swing.JPanel();
        filedJLable6 = new javax.swing.JLabel();
        detailTypeTextField6 = new learnway.components.TextField();
        typeAreajPanel6 = new javax.swing.JPanel();
        filedJLable7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        button1 = new learnway.components.Button();
        button2 = new learnway.components.Button();
        button3 = new learnway.components.Button();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Address");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add New Academic");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 10, 0));

        typeAreajPanel7.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable8.setFont(filedJLable8.getFont().deriveFont(filedJLable8.getFont().getSize()+2f));
        filedJLable8.setText("Line 01");
        typeAreajPanel7.add(filedJLable8);

        detailTypeTextField8.setFont(detailTypeTextField8.getFont().deriveFont(detailTypeTextField8.getFont().getSize()+2f));
        typeAreajPanel7.add(detailTypeTextField8);

        jPanel3.add(typeAreajPanel7);

        typeAreajPanel9.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable10.setFont(filedJLable10.getFont().deriveFont(filedJLable10.getFont().getSize()+2f));
        filedJLable10.setText("Line 02");
        typeAreajPanel9.add(filedJLable10);

        detailTypeTextField10.setFont(detailTypeTextField10.getFont().deriveFont(detailTypeTextField10.getFont().getSize()+2f));
        typeAreajPanel9.add(detailTypeTextField10);

        jPanel3.add(typeAreajPanel9);

        typeAreajPanel8.setLayout(new java.awt.GridLayout(2, 1));
        jPanel3.add(typeAreajPanel8);

        typeAreajPanel10.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable11.setFont(filedJLable11.getFont().deriveFont(filedJLable11.getFont().getSize()+2f));
        filedJLable11.setText("Province");
        typeAreajPanel10.add(filedJLable11);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeAreajPanel10.add(jComboBox2);

        jPanel3.add(typeAreajPanel10);

        typeAreajPanel11.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable12.setFont(filedJLable12.getFont().deriveFont(filedJLable12.getFont().getSize()+2f));
        filedJLable12.setText("District");
        typeAreajPanel11.add(filedJLable12);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeAreajPanel11.add(jComboBox3);

        jPanel3.add(typeAreajPanel11);

        typeAreajPanel12.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable13.setFont(filedJLable13.getFont().deriveFont(filedJLable13.getFont().getSize()+2f));
        filedJLable13.setText("City");
        typeAreajPanel12.add(filedJLable13);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeAreajPanel12.add(jComboBox4);

        jPanel3.add(typeAreajPanel12);

        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 5, 0));

        typeAreajPanel.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable1.setFont(filedJLable1.getFont().deriveFont(filedJLable1.getFont().getSize()+2f));
        filedJLable1.setText("First Name");
        typeAreajPanel.add(filedJLable1);

        detailTypeTextField1.setFont(detailTypeTextField1.getFont().deriveFont(detailTypeTextField1.getFont().getSize()+2f));
        typeAreajPanel.add(detailTypeTextField1);

        jPanel2.add(typeAreajPanel);

        typeAreajPanel1.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable2.setFont(filedJLable2.getFont().deriveFont(filedJLable2.getFont().getSize()+2f));
        filedJLable2.setText("Last Name");
        typeAreajPanel1.add(filedJLable2);

        detailTypeTextField2.setFont(detailTypeTextField2.getFont().deriveFont(detailTypeTextField2.getFont().getSize()+2f));
        typeAreajPanel1.add(detailTypeTextField2);

        jPanel2.add(typeAreajPanel1);

        typeAreajPanel2.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable3.setFont(filedJLable3.getFont().deriveFont(filedJLable3.getFont().getSize()+2f));
        filedJLable3.setText("NIC Number");
        typeAreajPanel2.add(filedJLable3);

        detailTypeTextField3.setFont(detailTypeTextField3.getFont().deriveFont(detailTypeTextField3.getFont().getSize()+2f));
        typeAreajPanel2.add(detailTypeTextField3);

        jPanel2.add(typeAreajPanel2);

        typeAreajPanel3.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable4.setFont(filedJLable4.getFont().deriveFont(filedJLable4.getFont().getSize()+2f));
        filedJLable4.setText("Mobile");
        typeAreajPanel3.add(filedJLable4);

        detailTypeTextField4.setFont(detailTypeTextField4.getFont().deriveFont(detailTypeTextField4.getFont().getSize()+2f));
        typeAreajPanel3.add(detailTypeTextField4);

        jPanel2.add(typeAreajPanel3);

        typeAreajPanel4.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable5.setFont(filedJLable5.getFont().deriveFont(filedJLable5.getFont().getSize()+2f));
        filedJLable5.setText("Email");
        typeAreajPanel4.add(filedJLable5);

        detailTypeTextField5.setFont(detailTypeTextField5.getFont().deriveFont(detailTypeTextField5.getFont().getSize()+2f));
        typeAreajPanel4.add(detailTypeTextField5);

        jPanel2.add(typeAreajPanel4);

        typeAreajPanel5.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable6.setFont(filedJLable6.getFont().deriveFont(filedJLable6.getFont().getSize()+2f));
        filedJLable6.setText("Password");
        typeAreajPanel5.add(filedJLable6);

        detailTypeTextField6.setFont(detailTypeTextField6.getFont().deriveFont(detailTypeTextField6.getFont().getSize()+2f));
        typeAreajPanel5.add(detailTypeTextField6);

        jPanel2.add(typeAreajPanel5);

        typeAreajPanel6.setLayout(new java.awt.GridLayout(2, 1));

        filedJLable7.setFont(filedJLable7.getFont().deriveFont(filedJLable7.getFont().getSize()+2f));
        filedJLable7.setText("Gender");
        typeAreajPanel6.add(filedJLable7);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeAreajPanel6.add(jComboBox1);

        jPanel2.add(typeAreajPanel6);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        button1.setBackground(new java.awt.Color(235, 59, 90));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Back");
        button1.setFont(button1.getFont().deriveFont(button1.getFont().getStyle() | java.awt.Font.BOLD, button1.getFont().getSize()+2));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(46, 204, 113));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Reset");
        button2.setFont(button2.getFont().deriveFont(button2.getFont().getStyle() | java.awt.Font.BOLD, button2.getFont().getSize()+2));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(52, 152, 219));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Add");
        button3.setFont(button3.getFont().deriveFont(button3.getFont().getStyle() | java.awt.Font.BOLD, button3.getFont().getSize()+2));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 577, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
      AcademicOverview v = new AcademicOverview(l);
   
      JPanel j =    l.getBody();
      j.removeAll();
      j.add(v);
      l.revalidate();
      l.repaint();
      
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private learnway.components.Button button1;
    private learnway.components.Button button2;
    private learnway.components.Button button3;
    private learnway.components.TextField detailTypeTextField1;
    private learnway.components.TextField detailTypeTextField10;
    private learnway.components.TextField detailTypeTextField2;
    private learnway.components.TextField detailTypeTextField3;
    private learnway.components.TextField detailTypeTextField4;
    private learnway.components.TextField detailTypeTextField5;
    private learnway.components.TextField detailTypeTextField6;
    private learnway.components.TextField detailTypeTextField8;
    private javax.swing.JLabel filedJLable1;
    private javax.swing.JLabel filedJLable10;
    private javax.swing.JLabel filedJLable11;
    private javax.swing.JLabel filedJLable12;
    private javax.swing.JLabel filedJLable13;
    private javax.swing.JLabel filedJLable2;
    private javax.swing.JLabel filedJLable3;
    private javax.swing.JLabel filedJLable4;
    private javax.swing.JLabel filedJLable5;
    private javax.swing.JLabel filedJLable6;
    private javax.swing.JLabel filedJLable7;
    private javax.swing.JLabel filedJLable8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel typeAreajPanel;
    private javax.swing.JPanel typeAreajPanel1;
    private javax.swing.JPanel typeAreajPanel10;
    private javax.swing.JPanel typeAreajPanel11;
    private javax.swing.JPanel typeAreajPanel12;
    private javax.swing.JPanel typeAreajPanel2;
    private javax.swing.JPanel typeAreajPanel3;
    private javax.swing.JPanel typeAreajPanel4;
    private javax.swing.JPanel typeAreajPanel5;
    private javax.swing.JPanel typeAreajPanel6;
    private javax.swing.JPanel typeAreajPanel7;
    private javax.swing.JPanel typeAreajPanel8;
    private javax.swing.JPanel typeAreajPanel9;
    // End of variables declaration//GEN-END:variables
}
