/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package learnway.view.admin;

import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;
import learnway.components.TableGradientCell;

/**
 *
 * @author Ishara Deshan
 */
public class InstructorDetails extends javax.swing.JPanel {

    /**
     * Creates new form StudentDetails
     */
    public InstructorDetails() {
        initComponents();
         JScrollBar verticalScrollBar = jScrollPane1.getVerticalScrollBar();
            verticalScrollBar.setUnitIncrement(16);  // Set the unit increment to a higher value
            verticalScrollBar.setBlockIncrement(50); // Set the block increment to a higher value

            // Optionally, speed up the horizontal scroll speed
            JScrollBar horizontalScrollBar = jScrollPane1.getHorizontalScrollBar();
            horizontalScrollBar.setUnitIncrement(16); // Set the unit increment to a higher value
            horizontalScrollBar.setBlockIncrement(50); // Set the block increment to a higher value
             jTable1.setDefaultRenderer(Object.class, new TableGradientCell());
//        jPanel1.putClientProperty(FlatClientProperties.STYLE, ""
//                + "border:1,1,1,1,$TableHeader.bottomSeparatorColor,,10");
        jTable1.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                + "separatorColor:$TableHeader.background");
        jScrollPane2.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:3,0,3,0,$Table.background,10,10");
        jScrollPane2.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverTrackColor:null");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        typingAreaJPanel1 = new javax.swing.JPanel();
        detailjLabel1 = new javax.swing.JLabel();
        textEnterField1 = new learnway.components.TextField();
        typingAreaJPanel2 = new javax.swing.JPanel();
        detailjLabel2 = new javax.swing.JLabel();
        textEnterField2 = new learnway.components.TextField();
        jPanel6 = new javax.swing.JPanel();
        typingAreaJPanel3 = new javax.swing.JPanel();
        detailjLabel3 = new javax.swing.JLabel();
        textEnterField3 = new learnway.components.TextField();
        typingAreaJPanel4 = new javax.swing.JPanel();
        detailjLabel4 = new javax.swing.JLabel();
        textEnterField4 = new learnway.components.TextField();
        typingAreaJPanel5 = new javax.swing.JPanel();
        detailjLabel5 = new javax.swing.JLabel();
        textEnterField5 = new learnway.components.TextField();
        jPanel3 = new javax.swing.JPanel();
        typingAreaJPanel6 = new javax.swing.JPanel();
        detailjLabel6 = new javax.swing.JLabel();
        textEnterField6 = new learnway.components.TextField();
        typingAreaJPanel7 = new javax.swing.JPanel();
        detailjLabel7 = new javax.swing.JLabel();
        textEnterField7 = new learnway.components.TextField();
        typingAreaJPanel8 = new javax.swing.JPanel();
        detailjLabel8 = new javax.swing.JLabel();
        textEnterField8 = new learnway.components.TextField();
        jPanel5 = new javax.swing.JPanel();
        typingAreaJPanel11 = new javax.swing.JPanel();
        detailjLabel11 = new javax.swing.JLabel();
        textEnterField9 = new learnway.components.TextField();
        typingAreaJPanel12 = new javax.swing.JPanel();
        detailjLabel12 = new javax.swing.JLabel();
        textEnterField10 = new learnway.components.TextField();
        typingAreaJPanel13 = new javax.swing.JPanel();
        detailjLabel13 = new javax.swing.JLabel();
        textEnterField11 = new learnway.components.TextField();
        typingAreaJPanel14 = new javax.swing.JPanel();
        detailjLabel14 = new javax.swing.JLabel();
        textEnterField12 = new learnway.components.TextField();
        typingAreaJPanel15 = new javax.swing.JPanel();
        detailjLabel15 = new javax.swing.JLabel();
        textEnterField13 = new learnway.components.TextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        button3 = new learnway.components.Button();
        button4 = new learnway.components.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane1.setToolTipText("");
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1075, 737));

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setText("Instructor Details");
        jPanel4.add(jLabel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 3, 10, 0));

        typingAreaJPanel1.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel1.setFont(detailjLabel1.getFont().deriveFont(detailjLabel1.getFont().getSize()+2f));
        detailjLabel1.setText("Line 01");
        typingAreaJPanel1.add(detailjLabel1);

        textEnterField1.setEnabled(false);
        textEnterField1.setFont(textEnterField1.getFont().deriveFont(textEnterField1.getFont().getSize()+2f));
        typingAreaJPanel1.add(textEnterField1);

        jPanel2.add(typingAreaJPanel1);

        typingAreaJPanel2.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel2.setFont(detailjLabel2.getFont().deriveFont(detailjLabel2.getFont().getSize()+2f));
        detailjLabel2.setText("Line 02");
        typingAreaJPanel2.add(detailjLabel2);

        textEnterField2.setEnabled(false);
        textEnterField2.setFont(textEnterField2.getFont().deriveFont(textEnterField2.getFont().getSize()+2f));
        typingAreaJPanel2.add(textEnterField2);

        jPanel2.add(typingAreaJPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        typingAreaJPanel3.setLayout(new java.awt.GridLayout(2, 1, 10, 0));

        detailjLabel3.setFont(detailjLabel3.getFont().deriveFont(detailjLabel3.getFont().getSize()+2f));
        detailjLabel3.setText("Province");
        typingAreaJPanel3.add(detailjLabel3);

        textEnterField3.setEnabled(false);
        textEnterField3.setFont(textEnterField3.getFont().deriveFont(textEnterField3.getFont().getSize()+2f));
        typingAreaJPanel3.add(textEnterField3);

        jPanel2.add(typingAreaJPanel3);

        typingAreaJPanel4.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel4.setFont(detailjLabel4.getFont().deriveFont(detailjLabel4.getFont().getSize()+2f));
        detailjLabel4.setText("District");
        typingAreaJPanel4.add(detailjLabel4);

        textEnterField4.setEnabled(false);
        textEnterField4.setFont(textEnterField4.getFont().deriveFont(textEnterField4.getFont().getSize()+2f));
        typingAreaJPanel4.add(textEnterField4);

        jPanel2.add(typingAreaJPanel4);

        typingAreaJPanel5.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel5.setFont(detailjLabel5.getFont().deriveFont(detailjLabel5.getFont().getSize()+2f));
        detailjLabel5.setText("City");
        typingAreaJPanel5.add(detailjLabel5);

        textEnterField5.setEnabled(false);
        textEnterField5.setFont(textEnterField5.getFont().deriveFont(textEnterField5.getFont().getSize()+2f));
        typingAreaJPanel5.add(textEnterField5);

        jPanel2.add(typingAreaJPanel5);

        detailjLabel6.setFont(detailjLabel6.getFont().deriveFont(detailjLabel6.getFont().getStyle() | java.awt.Font.BOLD, detailjLabel6.getFont().getSize()+3));
        detailjLabel6.setText("NIC :");

        textEnterField6.setText("200531101004");
        textEnterField6.setEnabled(false);
        textEnterField6.setFont(textEnterField6.getFont().deriveFont(textEnterField6.getFont().getSize()+2f));
        textEnterField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typingAreaJPanel6Layout = new javax.swing.GroupLayout(typingAreaJPanel6);
        typingAreaJPanel6.setLayout(typingAreaJPanel6Layout);
        typingAreaJPanel6Layout.setHorizontalGroup(
            typingAreaJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typingAreaJPanel6Layout.createSequentialGroup()
                .addComponent(detailjLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(textEnterField6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        typingAreaJPanel6Layout.setVerticalGroup(
            typingAreaJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typingAreaJPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(detailjLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingAreaJPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textEnterField6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        detailjLabel7.setFont(detailjLabel7.getFont().deriveFont(detailjLabel7.getFont().getStyle() | java.awt.Font.BOLD, detailjLabel7.getFont().getSize()+3));
        detailjLabel7.setText("Registered Date :");

        textEnterField7.setText("2005-11-06");
        textEnterField7.setEnabled(false);
        textEnterField7.setFont(textEnterField7.getFont().deriveFont(textEnterField7.getFont().getSize()+2f));
        textEnterField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typingAreaJPanel7Layout = new javax.swing.GroupLayout(typingAreaJPanel7);
        typingAreaJPanel7.setLayout(typingAreaJPanel7Layout);
        typingAreaJPanel7Layout.setHorizontalGroup(
            typingAreaJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typingAreaJPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailjLabel7)
                .addGap(15, 15, 15)
                .addComponent(textEnterField7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        typingAreaJPanel7Layout.setVerticalGroup(
            typingAreaJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingAreaJPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(detailjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingAreaJPanel7Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(textEnterField7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        detailjLabel8.setFont(detailjLabel8.getFont().deriveFont(detailjLabel8.getFont().getStyle() | java.awt.Font.BOLD, detailjLabel8.getFont().getSize()+3));
        detailjLabel8.setText("Activity Status :");

        textEnterField8.setText("Inactive");
        textEnterField8.setEnabled(false);
        textEnterField8.setFont(textEnterField8.getFont().deriveFont(textEnterField8.getFont().getSize()+2f));
        textEnterField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typingAreaJPanel8Layout = new javax.swing.GroupLayout(typingAreaJPanel8);
        typingAreaJPanel8.setLayout(typingAreaJPanel8Layout);
        typingAreaJPanel8Layout.setHorizontalGroup(
            typingAreaJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typingAreaJPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailjLabel8)
                .addGap(15, 15, 15)
                .addComponent(textEnterField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        typingAreaJPanel8Layout.setVerticalGroup(
            typingAreaJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingAreaJPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(detailjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typingAreaJPanel8Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(textEnterField8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(typingAreaJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(typingAreaJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addComponent(typingAreaJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typingAreaJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typingAreaJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(typingAreaJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setLayout(new java.awt.GridLayout(2, 3, 10, 0));

        typingAreaJPanel11.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel11.setFont(detailjLabel11.getFont().deriveFont(detailjLabel11.getFont().getSize()+2f));
        detailjLabel11.setText("First Name");
        typingAreaJPanel11.add(detailjLabel11);

        textEnterField9.setEnabled(false);
        textEnterField9.setFont(textEnterField9.getFont().deriveFont(textEnterField9.getFont().getSize()+2f));
        typingAreaJPanel11.add(textEnterField9);

        jPanel5.add(typingAreaJPanel11);

        typingAreaJPanel12.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel12.setFont(detailjLabel12.getFont().deriveFont(detailjLabel12.getFont().getSize()+2f));
        detailjLabel12.setText("Last Name");
        typingAreaJPanel12.add(detailjLabel12);

        textEnterField10.setEnabled(false);
        textEnterField10.setFont(textEnterField10.getFont().deriveFont(textEnterField10.getFont().getSize()+2f));
        typingAreaJPanel12.add(textEnterField10);

        jPanel5.add(typingAreaJPanel12);

        typingAreaJPanel13.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel13.setFont(detailjLabel13.getFont().deriveFont(detailjLabel13.getFont().getSize()+2f));
        detailjLabel13.setText("Mobile");
        typingAreaJPanel13.add(detailjLabel13);

        textEnterField11.setEnabled(false);
        textEnterField11.setFont(textEnterField11.getFont().deriveFont(textEnterField11.getFont().getSize()+2f));
        typingAreaJPanel13.add(textEnterField11);

        jPanel5.add(typingAreaJPanel13);

        typingAreaJPanel14.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel14.setFont(detailjLabel14.getFont().deriveFont(detailjLabel14.getFont().getSize()+2f));
        detailjLabel14.setText("Email");
        typingAreaJPanel14.add(detailjLabel14);

        textEnterField12.setEnabled(false);
        textEnterField12.setFont(textEnterField12.getFont().deriveFont(textEnterField12.getFont().getSize()+2f));
        typingAreaJPanel14.add(textEnterField12);

        jPanel5.add(typingAreaJPanel14);

        typingAreaJPanel15.setLayout(new java.awt.GridLayout(2, 1));

        detailjLabel15.setFont(detailjLabel15.getFont().deriveFont(detailjLabel15.getFont().getSize()+2f));
        detailjLabel15.setText("Gender");
        typingAreaJPanel15.add(detailjLabel15);

        textEnterField13.setEnabled(false);
        textEnterField13.setFont(textEnterField13.getFont().deriveFont(textEnterField13.getFont().getSize()+2f));
        typingAreaJPanel15.add(textEnterField13);

        jPanel5.add(typingAreaJPanel15);

        jPanel8.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+4));
        jLabel3.setText("Class");
        jPanel8.add(jLabel3);
        jPanel8.add(jSeparator3);

        button3.setBackground(new java.awt.Color(235, 59, 90));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Back");
        button3.setFont(button3.getFont().deriveFont(button3.getFont().getStyle() | java.awt.Font.BOLD, button3.getFont().getSize()+2));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(52, 152, 219));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setText("Edit");
        button4.setFont(button4.getFont().deriveFont(button4.getFont().getStyle() | java.awt.Font.BOLD, button4.getFont().getSize()+2));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setFont(jTable1.getFont().deriveFont(jTable1.getFont().getSize()+2f));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Class", "Registered Date", "Student Count", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+4));
        jLabel4.setText("Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(865, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textEnterField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterField6ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void textEnterField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterField7ActionPerformed

    private void textEnterField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterField8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private learnway.components.Button button3;
    private learnway.components.Button button4;
    private javax.swing.JLabel detailjLabel1;
    private javax.swing.JLabel detailjLabel11;
    private javax.swing.JLabel detailjLabel12;
    private javax.swing.JLabel detailjLabel13;
    private javax.swing.JLabel detailjLabel14;
    private javax.swing.JLabel detailjLabel15;
    private javax.swing.JLabel detailjLabel2;
    private javax.swing.JLabel detailjLabel3;
    private javax.swing.JLabel detailjLabel4;
    private javax.swing.JLabel detailjLabel5;
    private javax.swing.JLabel detailjLabel6;
    private javax.swing.JLabel detailjLabel7;
    private javax.swing.JLabel detailjLabel8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private learnway.components.TextField textEnterField1;
    private learnway.components.TextField textEnterField10;
    private learnway.components.TextField textEnterField11;
    private learnway.components.TextField textEnterField12;
    private learnway.components.TextField textEnterField13;
    private learnway.components.TextField textEnterField2;
    private learnway.components.TextField textEnterField3;
    private learnway.components.TextField textEnterField4;
    private learnway.components.TextField textEnterField5;
    private learnway.components.TextField textEnterField6;
    private learnway.components.TextField textEnterField7;
    private learnway.components.TextField textEnterField8;
    private learnway.components.TextField textEnterField9;
    private javax.swing.JPanel typingAreaJPanel1;
    private javax.swing.JPanel typingAreaJPanel11;
    private javax.swing.JPanel typingAreaJPanel12;
    private javax.swing.JPanel typingAreaJPanel13;
    private javax.swing.JPanel typingAreaJPanel14;
    private javax.swing.JPanel typingAreaJPanel15;
    private javax.swing.JPanel typingAreaJPanel2;
    private javax.swing.JPanel typingAreaJPanel3;
    private javax.swing.JPanel typingAreaJPanel4;
    private javax.swing.JPanel typingAreaJPanel5;
    private javax.swing.JPanel typingAreaJPanel6;
    private javax.swing.JPanel typingAreaJPanel7;
    private javax.swing.JPanel typingAreaJPanel8;
    // End of variables declaration//GEN-END:variables
}
